### ISSUE TITLE
calling PG load_file many times might be quite slow

### ISSUE THREAD

**Issue by chapmanjacobd** [guillaumeblaquiere/workflow-bq-to-cloudsql#1]
https://github.com/guillaumeblaquiere/workflow-bq-to-cloudsql/blob/0f871d8e0679464ccbf30b601e8fc512b3d33b53/import.yaml#L56

I haven't used GCP workflows before but my intuition leads me to believe that if you can merge the csv files before importing them then it will be a lot faster to import to postgres. 

This may not be an issue for you (if BQ export was only creating a few shards) but if you had clustering set on a GEOGRAPHY type column BigQuery was creating tens of thousands and even hundreds of thousands of shards in my experience.

https://stackoverflow.com/a/59444472/14598384

if you KNOW you will always have fewer than 32 shards this might be another option but I think the time improvement won't justify the uncertainty in this case (sharding is uncontrollable) https://stackoverflow.com/questions/55114393/google-cloud-storage-joining-multiple-csv-files

**Comment by guillaumeblaquiere** [comment]
I would like to keep the workflow simple enough to present it in my article.

But, indeed, using the Compose feature of Cloud Storage to reduce the number of files to import at the end is a very good idea. 

I will see to create another workflow file example with that update. Or you can submit it.

**Comment by guillaumeblaquiere** [comment]
@chapmanjacobd I [wrote another article](https://medium.com/google-cloud/get-a-single-one-csv-file-with-bigquery-export-956d2a147886), with [another workflow sample](https://github.com/guillaumeblaquiere/workflow-bq-export-to-one-csv). Merge them to create a powerful solution!!
